version: "3"

services:
    descomplicafront:
        build: .
        command: npm start
        ports: 
            - "3000:3000"
        volumes:
            - .:/app
            - '/app/node_modules'